---
- hosts:  all
  become: yes
  tasks:
    - name: Install wget
      apt:
       name: "{{mywebserverpackonubuntu}}"
       state: present
      when: ansible_os_family== "Debian"

    - name: Install webserver on redhat
      yum:
       name: "{{mywebserverpackonredhat}}"
       state: present
      when: ansible_os_family== "RedHat"        
    
    - name: Start webserver on Redhat
      service:
        name: "{{mywebserverpackonredhat}}"
        state: started
      when: ansible_os_family== "Redhat"  
